### ISSUE TITLE
Numerous Small Stuff

### ISSUE THREAD

**Issue by KyleSmith0905** [MODDED-OFFICIAL/extracolors#3]
My power is out due to a storm in Florida so I have nothing else to do… I have some suggestions about your mod…

## Small Changes
I am not a professional programmer, but might as well mass-dump suggestions here. 🤓
- Add disclaimer from [here](https://www.innersloth.com/modpolicy.php)
- Change note.txt extracolors/Extra Colors to README.md. I think README.md always appear in GitHub when the parent folder is open, (it won’t be missed). 🤔
- Maybe move some functions from extracolors/Extra Colors/ExtraColors/ExtraColors.cs to other folders, exactly what you were doing with the ping tracker.😃

**Comment by Bossgamerteam** [comment]
I have and Thanks for these suggestions 😄
